Updated readme
odota/mobile pull request #121
Opened 2018-03-06 07:26 UTC by cs-miller

I removed references to installing the beta, and replaced them with links to the App Store and Play Store.

2018-03-06 08:13 UTC, dkwl93 commented
LGTM - Would like @Proyoyo to review properly though.

2018-03-07 00:10 UTC, Proyoyo commented
@cs-miller There's some padding on the Google Play badge. Should we put them on different line to make it look better?

<img width="477" alt="screen shot 2018-03-07 at 11 09 48 am" src="https://user-images.githubusercontent.com/11515661/37066152-1f0058e8-21f8-11e8-8939-879360cf5615.png">

2018-03-07 00:16 UTC, Proyoyo requested changes

2018-03-07 00:16 UTC, Proyoyo commented on README.md
>  * Still a work in progress
We can remove this section for now.

2018-03-07 00:16 UTC, Proyoyo commented on README.md
> +<a href='https://play.google.com/store/apps/details?id=com.opendota.mobile&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1' ><img alt='Get it on Google Play' src='https://play.google
Can we add the Google Play badge to a different line? It looks janky because it has padding while Apple's doesn't.

2018-03-07 00:38 UTC, Proyoyo approved these changes

2018-03-07 00:38 UTC, merged