Heatmap
odota/mobile pull request #84
Opened 2017-11-17 04:28 UTC by vocosu

Finished heatmap

2017-11-19 23:29 UTC, Proyoyo commented
@vocosu Everything looks great on Android. However, on iOS, there's some scaling issues.

![asset](https://user-images.githubusercontent.com/11515661/32996909-44cd4172-cddd-11e7-95fc-4eb97977b32f.png)

![asset 1](https://user-images.githubusercontent.com/11515661/32996916-54252298-cddd-11e7-91f3-035be904ca90.png)

As you can see, this only happens to several player. I tested this on both iPhone 5S and iPhone 6s+. Is it possible for you to try and debug this in Xcode?


In addition, we should probably provide different map images based on the patch version. This is already implemented in the ui repo.

2017-11-19 23:55 UTC, vocosu commented
For your first question, I don't have a Mac or iOS device so might take me a little longer to solve that issue. I'll try to set up a VM this week so I can start debugging in Xcode.

I can definitely add the different map images based on the patch version though.

2017-11-19 23:59 UTC, Proyoyo commented
@vocosu Gotcha. And don't forget to pull from master before submitting the PR. I have updated master with 7.07 compatibility.

I'll spend most of my time this week fixing the bugs that were found by the open beta testers (e.g. iPhone X compatibility, custom font issue). Once I'm done with that, I can help you with the iOS debugging.

2017-11-21 22:56 UTC, vocosu commented
@Proyoyo  I have implemented changing the map image based on the patch version.

Still stuck on the iOS bug due to issues setting up my VM. I'll have access to an iOS device this weekend though. Let me know when you can help me on the iOS debugging.

2017-11-21 23:00 UTC, Proyoyo commented
Looks good! I can probably help with iOS debugging later today or tomorrow.

2017-11-22 02:03 UTC, Proyoyo commented on app/components/Heatmap.js
> +            script = heatmapInputGenerator(JSON.stringify(adjustedData), width, this.getMap(this.props.starTime));
This should be this.props.startTime

2017-11-22 02:04 UTC, Proyoyo commented on app/containers/MatchLaning.js
> +                        startTime={this.props.matchDetails.startTime}
This should be change to this.props.matchDetails.start_time

2017-11-22 02:05 UTC, Proyoyo requested changes
The map based on game start time doesn't work. I've added a few comments with the instruction on how to fix it.

2017-11-22 02:20 UTC, vocosu commented on app/containers/MatchLaning.js
> +                        startTime={this.props.matchDetails.startTime}
Good catch. Just squashed the fix into the same commit.

2017-11-22 02:20 UTC, vocosu commented on app/components/Heatmap.js
> +            script = heatmapInputGenerator(JSON.stringify(adjustedData), width, this.getMap(this.props.starTime));
Fixed.

2017-11-22 03:07 UTC, Proyoyo commented
I've tried it on iOS and now the image doesn't get rendered anymore. I've removed the XCode reference to detailed.png and added new XCode references to the new map images. However, this doesn't solve the issue. I'll investigate this further tomorrow.

![asset 2](https://user-images.githubusercontent.com/11515661/33108052-397f772e-cf8e-11e7-9977-8423e7281b39.png)

2017-11-27 03:31 UTC, vocosu commented
UPDATE: I have access to a Mac OS X now. I'll see if I can debug this on Xcode this week.

2018-01-03 10:22 UTC, anhmiuhv commented
I made a bug fixes in this branch
#101

2018-01-04 00:34 UTC, vocosu commented
Closing due to https://github.com/odota/mobile/pull/101.

2018-01-04 00:34 UTC, closed without merging